export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api/v1',
  TIMEOUT: 30000,
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/Auth/login',
    REGISTER: '/Auth/register',
    REGISTER_TENANT: '/Auth/register-tenant',
    REFRESH_TOKEN: '/Auth/refresh-token',
    ME: '/Auth/me',
    CHANGE_PASSWORD: '/Auth/change-password',
    SEND_EMAIL_VERIFICATION: '/Auth/send-email-verification',
    VERIFY_EMAIL: '/Auth/verify-email',
    FORGOT_PASSWORD: '/Auth/forgot-password',
    RESET_PASSWORD: '/Auth/reset-password',
    SETUP_2FA: '/Auth/2fa/setup',
    VERIFY_2FA: '/Auth/2fa/verify',
    DISABLE_2FA: '/Auth/2fa/disable',
    INVITE_USER: '/Auth/invite',
    ACCEPT_INVITE: '/Auth/accept-invite',
    INVITATIONS: '/Auth/invitations',
    REVOKE_INVITATION: (id: string) => `/Auth/invitations/${id}`,
    SESSIONS: '/Auth/sessions',
    SESSION: (id: string) => `/Auth/sessions/${id}`,
    LOGIN_HISTORY: '/Auth/login-history',
  },
  USERS: {
    LIST: '/Users',
    DETAIL: (id: string) => `/Users/${id}`,
    ACTIVATE: (id: string) => `/Users/${id}/activate`,
    SUSPEND: (id: string) => `/Users/${id}/suspend`,
    DEACTIVATE: (id: string) => `/Users/${id}/deactivate`,
    UNLOCK: (id: string) => `/Users/${id}/unlock`,
  },
  ROLES: {
    LIST: '/Roles',
    DETAIL: (id: string) => `/Roles/${id}`,
    PERMISSIONS: (id: string) => `/Roles/${id}/permissions`,
    ASSIGN_USER: (roleId: string, userId: string) => `/Roles/${roleId}/users/${userId}`,
    REMOVE_USER: (roleId: string, userId: string) => `/Roles/${roleId}/users/${userId}`,
    ASSIGNABLE: '/Roles/assignable',
  },
  TENANTS: {
    LIST: '/Tenants',
    DETAIL: (id: string) => `/Tenants/${id}`,
    ACTIVATE: (id: string) => `/Tenants/${id}/activate`,
    SUSPEND: (id: string) => `/Tenants/${id}/suspend`,
    DEACTIVATE: (id: string) => `/Tenants/${id}/deactivate`,
    BRANDING: (id: string) => `/Tenants/${id}/branding`,
    BUSINESS_INFO: (id: string) => `/Tenants/${id}/business-info`,
    CUSTOM_TEXT: (id: string) => `/Tenants/${id}/custom-text`,
    PUBLIC_BRANDING: '/Tenants/branding',
    DEFAULT_ROLE: (id: string) => `/Tenants/${id}/default-role`,
  },
  PERMISSIONS: {
    LIST: '/Permissions',
  },
  AUDIT_LOGS: {
    LIST: '/AuditLogs',
  },
  NOTIFICATIONS: {
    LIST: '/Notifications',
    UNREAD_COUNT: '/Notifications/unread-count',
    MARK_READ: (id: string) => `/Notifications/${id}/read`,
    MARK_ALL_READ: '/Notifications/read-all',
    PREFERENCES: '/Notifications/preferences',
  },
  FILES: {
    LIST: '/Files',
    UPLOAD: '/Files',
    UPLOAD_TEMP: '/Files/upload-temp',
    DETAIL: (id: string) => `/Files/${id}`,
    URL: (id: string) => `/Files/${id}/url`,
    DELETE: (id: string) => `/Files/${id}`,
  },
  REPORTS: {
    LIST: '/Reports',
    REQUEST: '/Reports',
    DOWNLOAD: (id: string) => `/Reports/${id}/download`,
    DELETE: (id: string) => `/Reports/${id}`,
  },
  SETTINGS: {
    LIST: '/Settings',
    UPDATE: '/Settings',
    UPDATE_SINGLE: (key: string) => `/Settings/${key}`,
  },
  API_KEYS: {
    LIST: '/ApiKeys',
    DETAIL: (id: string) => `/ApiKeys/${id}`,
    EMERGENCY_REVOKE: (id: string) => `/ApiKeys/${id}/emergency-revoke`,
  },
  FEATURE_FLAGS: {
    LIST: '/FeatureFlags',
    BY_KEY: (key: string) => `/FeatureFlags/${key}`,
    RESOLVE: (key: string) => `/FeatureFlags/resolve/${key}`,
    DETAIL: (id: string) => `/FeatureFlags/${id}`,
    TENANT_OVERRIDE: (id: string, tenantId: string) => `/FeatureFlags/${id}/tenants/${tenantId}`,
    OPT_OUT: (id: string) => `/FeatureFlags/${id}/opt-out`,
  },
  WEBHOOKS: {
    LIST: '/Webhooks',
    DETAIL: (id: string) => `/Webhooks/${id}`,
    DELIVERIES: (id: string) => `/Webhooks/${id}/deliveries`,
    TEST: (id: string) => `/Webhooks/${id}/test`,
    EVENTS: '/Webhooks/events',
    ADMIN: '/Webhooks/admin',
    ADMIN_STATS: '/Webhooks/admin/stats',
    ADMIN_DELIVERIES: (endpointId: string) => `/Webhooks/admin/${endpointId}/deliveries`,
  },
  BILLING: {
    PLANS: '/Billing/plans',
    PLANS_MANAGE: '/Billing/plans/manage',
    PLANS_CREATE: '/Billing/plans/create',
    PLAN_DETAIL: (id: string) => `/Billing/plans/${id}`,
    PLAN_RESYNC: (id: string) => `/Billing/plans/${id}/resync`,
    SUBSCRIPTION: '/Billing/subscription',
    CHANGE_PLAN: '/Billing/change-plan',
    CANCEL: '/Billing/cancel',
    PAYMENTS: '/Billing/payments',
    USAGE: '/Billing/usage',
    TENANT_SUBSCRIPTION: (tenantId: string) => `/Billing/tenants/${tenantId}/subscription`,
    TENANT_CHANGE_PLAN: (tenantId: string) => `/Billing/tenants/${tenantId}/change-plan`,
    SUBSCRIPTIONS: '/Billing/subscriptions',
    TENANT_USAGE: (tenantId: string) => `/Billing/tenants/${tenantId}/usage`,
    TENANT_PAYMENTS: (tenantId: string) => `/Billing/tenants/${tenantId}/payments`,
    PLAN_OPTIONS: '/Billing/plan-options',
  },
  PRODUCTS: {
    LIST: '/Products',
    DETAIL: (id: string) => `/Products/${id}`,
    PUBLISH: (id: string) => `/Products/${id}/publish`,
    ARCHIVE: (id: string) => `/Products/${id}/archive`,
    IMAGE: (id: string) => `/Products/${id}/image`,
  },
  IMPORT_EXPORT: {
    TYPES: '/ImportExport/types',
    TEMPLATE: (type: string) => `/ImportExport/${type}/template`,
    PREVIEW: '/ImportExport/preview',
    IMPORT: '/ImportExport/import',
    IMPORTS: '/ImportExport/imports',
    IMPORT_DETAIL: (id: string) => `/ImportExport/imports/${id}`,
    IMPORT_ERRORS: (id: string) => `/ImportExport/imports/${id}/errors`,
  },
  COMMENTS_ACTIVITY: {
    COMMENTS: '/CommentsActivity/comments',
    COMMENT_DETAIL: (id: string) => `/CommentsActivity/comments/${id}`,
    COMMENT_REACTIONS: (id: string) => `/CommentsActivity/comments/${id}/reactions`,
    COMMENT_REACTION: (id: string, reactionType: string) => `/CommentsActivity/comments/${id}/reactions/${reactionType}`,
    ACTIVITY: '/CommentsActivity/activity',
    TIMELINE: '/CommentsActivity/timeline',
    WATCHERS_STATUS: '/CommentsActivity/watchers/status',
    WATCHERS: '/CommentsActivity/watchers',
    MENTIONABLE_USERS: '/CommentsActivity/mentionable-users',
  },
} as const;
