export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api/v1',
  TIMEOUT: 30000,
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/Auth/login',
    REGISTER: '/Auth/register',
    REGISTER_TENANT: '/Auth/register-tenant',
    REFRESH_TOKEN: '/Auth/refresh-token',
    ME: '/Auth/me',
    CHANGE_PASSWORD: '/Auth/change-password',
    SEND_EMAIL_VERIFICATION: '/Auth/send-email-verification',
    VERIFY_EMAIL: '/Auth/verify-email',
    FORGOT_PASSWORD: '/Auth/forgot-password',
    RESET_PASSWORD: '/Auth/reset-password',
    SETUP_2FA: '/Auth/2fa/setup',
    VERIFY_2FA: '/Auth/2fa/verify',
    DISABLE_2FA: '/Auth/2fa/disable',
    INVITE_USER: '/Auth/invite',
    ACCEPT_INVITE: '/Auth/accept-invite',
    INVITATIONS: '/Auth/invitations',
    REVOKE_INVITATION: (id: string) => `/Auth/invitations/${id}`,
    SESSIONS: '/Auth/sessions',
    SESSION: (id: string) => `/Auth/sessions/${id}`,
    LOGIN_HISTORY: '/Auth/login-history',
  },
  USERS: {
    LIST: '/Users',
    DETAIL: (id: string) => `/Users/${id}`,
    ACTIVATE: (id: string) => `/Users/${id}/activate`,
    SUSPEND: (id: string) => `/Users/${id}/suspend`,
    DEACTIVATE: (id: string) => `/Users/${id}/deactivate`,
    UNLOCK: (id: string) => `/Users/${id}/unlock`,
  },
  ROLES: {
    LIST: '/Roles',
    DETAIL: (id: string) => `/Roles/${id}`,
    PERMISSIONS: (id: string) => `/Roles/${id}/permissions`,
    ASSIGN_USER: (roleId: string, userId: string) => `/Roles/${roleId}/users/${userId}`,
    REMOVE_USER: (roleId: string, userId: string) => `/Roles/${roleId}/users/${userId}`,
  },
  TENANTS: {
    LIST: '/Tenants',
    DETAIL: (id: string) => `/Tenants/${id}`,
    ACTIVATE: (id: string) => `/Tenants/${id}/activate`,
    SUSPEND: (id: string) => `/Tenants/${id}/suspend`,
    DEACTIVATE: (id: string) => `/Tenants/${id}/deactivate`,
  },
  PERMISSIONS: {
    LIST: '/Permissions',
  },
  AUDIT_LOGS: {
    LIST: '/AuditLogs',
  },
  NOTIFICATIONS: {
    LIST: '/Notifications',
    UNREAD_COUNT: '/Notifications/unread-count',
    MARK_READ: (id: string) => `/Notifications/${id}/read`,
    MARK_ALL_READ: '/Notifications/read-all',
    PREFERENCES: '/Notifications/preferences',
  },
  FILES: {
    LIST: '/Files',
    UPLOAD: '/Files',
    DETAIL: (id: string) => `/Files/${id}`,
    URL: (id: string) => `/Files/${id}/url`,
    DELETE: (id: string) => `/Files/${id}`,
  },
  REPORTS: {
    LIST: '/Reports',
    REQUEST: '/Reports',
    DOWNLOAD: (id: string) => `/Reports/${id}/download`,
    DELETE: (id: string) => `/Reports/${id}`,
  },
  SETTINGS: {
    LIST: '/Settings',
    UPDATE: '/Settings',
    UPDATE_SINGLE: (key: string) => `/Settings/${key}`,
  },
} as const;
