import { billingModule } from '@/features/billing';
import { webhooksModule } from '@/features/webhooks';
import { importExportModule } from '@/features/import-export';
import { productsModule } from '@/features/products';
import { commentsActivityModule } from '@/features/comments-activity';
import { communicationModule } from '@/features/communication';
import { workflowModule } from '@/features/workflow';
import { registerWebModules, type WebModule } from '@/lib/modules';

/**
 * Optional module registry. This file is generated by the source-mode composer
 * in generated apps. In the template, all source modules are active.
 *
 * Core features (Files, Notifications, FeatureFlags, ApiKeys, AuditLogs,
 * Reports) are not in this list because they ship with every build.
 */

// Static catalog union — does not vary by selection. The generator always
// emits all 8 ids so that callers using ModuleName get a stable type.
export type ModuleName =
  | 'ai'
  | 'billing'
  | 'webhooks'
  | 'importExport'
  | 'products'
  | 'commentsActivity'
  | 'communication'
  | 'workflow';

// Source of truth for what's active in this build. The generator emits
// only the imports for modules included via `-Modules`; everything else
// is absent from this list (and its source files have been deleted).
export const enabledModules: WebModule[] = [
  billingModule,
  webhooksModule,
  importExportModule,
  productsModule,
  commentsActivityModule,
  communicationModule,
  workflowModule,
];

const enabledIds = new Set<string>(enabledModules.map((m) => m.id));

export function isModuleActive(module: ModuleName): boolean {
  return enabledIds.has(module);
}

// Frozen literal view derived from enabledModules. Kept for callers that
// read the map directly (e.g. `activeModules.workflow`); cannot drift from
// enabledModules because every flag is computed from enabledIds.
export const activeModules: Readonly<Record<ModuleName, boolean>> = Object.freeze({
  ai: isModuleActive('ai'),
  billing: isModuleActive('billing'),
  webhooks: isModuleActive('webhooks'),
  importExport: isModuleActive('importExport'),
  products: isModuleActive('products'),
  commentsActivity: isModuleActive('commentsActivity'),
  communication: isModuleActive('communication'),
  workflow: isModuleActive('workflow'),
});

export function registerAllModules(): void {
  registerWebModules(enabledModules);
}
