services:
  postgres:
    image: postgres:16-alpine
    container_name: starter-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: starterdb
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: starter-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: starter-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: starter-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: starter-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  jaeger:
    image: jaegertracing/jaeger:2.16.0
    container_name: starter-jaeger
    networks:
      backend:
        aliases: [spm_metrics_source]
    volumes:
      - ./jaeger-config.yaml:/etc/jaeger/config.yaml
    command: ["--config", "/etc/jaeger/config.yaml"]
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.10.0
    container_name: starter-prometheus
    networks:
      - backend
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-rules.yml:/etc/prometheus/rules.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

networks:
  backend:

volumes:
  postgres-data:
  minio-data:
  prometheus-data:
